//
// Created by alexus on 20.01.24.
//

#ifndef CPPGENERATOR_H
#define CPPGENERATOR_H
#include <project/generators/GeneratorElement.h>

namespace PROJECT_CORE {
class CppGenerator {
	std::vector<std::string> includes;
	std::vector<GeneratorElement*> elements;

public:
	[[nodiscard]] const std::vector<std::string> &getIncludes() const { return includes; }

	void setIncludes(const std::vector<std::string> &pIncludes) { includes = pIncludes; }

	void addInclude(const std::string &pInclude) { includes.emplace_back(pInclude); }

	[[nodiscard]] const std::vector<GeneratorElement*> &getElements() const { return elements; }

	void setElements(const std::vector<GeneratorElement*> &pElements) { elements = pElements; }

	void addElement(GeneratorElement* pElement) { elements.emplace_back(pElement); }

	std::string getFileCode() const {
		std::stringstream ss;
		//language=cpp
		ss << R"(/*
 * This file is automatically generated. DO NOT EDIT! Your changes will be overwritten by the editor.
 */
)";
		for (const auto &include: includes) { ss << std::format("#include <{}>\n", include); }
		ss << "\n";

		for (const auto &element: elements) { ss << element->getDefinition(0); }
		return ss.str();
	}

	n::engine::utils::ReportMessageUPtr saveFile(const std::filesystem::path &pPath) const {
		create_directories(pPath.parent_path());
		std::ofstream stream;
		try {
			stream.exceptions(std::_S_badbit | std::_S_eofbit | std::_S_failbit);
			stream.open(pPath);
		} catch (...) {

			auto msg = n::engine::utils::ReportMessage::create();
			msg->setTitle("Failed to save cpp file.");
			msg->setMessage("Exception thrown");
			msg->addInfoLine("Trying to save file at {}", pPath.string());
			return msg;
		}
		stream << getFileCode() << std::endl;
		return nullptr;
	}
};
} // namespace PROJECT_CORE


#endif //CPPGENERATOR_H
